[package]
name = "flutterrustnative"
version = "0.1.0"
edition = "2021"


[lib]
name = "flutterrustnative"
crate-type = ["cdylib", "staticlib"]


[dependencies]
flutter_rust_bridge = "1.80.1"
flutter_rust_bridge_macros = "1.80.1"
